# Generated by Django 5.2.6 on 2025-09-25 07:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.IntegerField(verbose_name='Nummer')),
            ],
            options={
                'verbose_name': 'Grundstück',
                'verbose_name_plural': 'Grundstücke',
            },
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Grundstückseigentümer',
                'verbose_name_plural': 'Grundstückseigentümer',
            },
        ),
        migrations.CreateModel(
            name='PropertyPropertyOwner',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Grundstück-Grundstücksbesitzer-Zuordnung',
                'verbose_name_plural': 'Grundstück-Grundstückbesitzer-Zuordnung',
            },
        ),
    ]
