# Generated by Django 5.2.6 on 2025-09-19 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastre', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyowner',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_property_owner', to='persons.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='properties',
            field=models.ManyToManyField(related_name='properties_owners', to='cadastre.property', verbose_name='Grundstück'),
        ),
        migrations.AddField(
            model_name='property',
            name='owners',
            field=models.ManyToManyField(related_name='owners_properties', to='cadastre.propertyowner', verbose_name='Besitzer'),
        ),
        migrations.AddField(
            model_name='propertypropertyowner',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastre.property', verbose_name='Grundstück'),
        ),
        migrations.AddField(
            model_name='propertypropertyowner',
            name='property_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastre.propertyowner', verbose_name='Grundstücksbesitzer'),
        ),
    ]
