# Generated by Django 5.2.6 on 2025-09-25 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propertyowner',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='propertyowner',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propertypropertyowner',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='propertypropertyowner',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
