# Generated by Django 5.2.6 on 2025-09-25 07:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('street', models.CharField(max_length=100, verbose_name='Straße')),
                ('door', models.CharField(max_length=100, verbose_name='Tür')),
                ('zipcode', models.CharField(max_length=10, null=True, verbose_name='Postleitzahl')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='Stadt')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
            },
        ),
        migrations.CreateModel(
            name='AddressCompany',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Adresse-Person-Zuordnung',
                'verbose_name_plural': 'Adresse-Person-Zuordnungen',
            },
        ),
        migrations.CreateModel(
            name='AddressPerson',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Adresse-Person-Zuordnung',
                'verbose_name_plural': 'Adresse-Person-Zuordnungen',
            },
        ),
    ]
