# Generated by Django 5.2.6 on 2025-09-25 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georeferenced_data', '0001_initial'),
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_address', to='lookups.country', verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state_address', to='lookups.state', verbose_name='Bundesland'),
        ),
        migrations.AddField(
            model_name='addresscompany',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='georeferenced_data.address', verbose_name='Adresse'),
        ),
    ]
