# Generated by Django 5.2.6 on 2025-09-19 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georeferenced_data', '0002_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresscompany',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='persons.company', verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='address',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='companies_addresses', through='georeferenced_data.AddressCompany', to='persons.company', verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='addressperson',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='georeferenced_data.address', verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='addressperson',
            name='person',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='persons.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='persons_addresses', through='georeferenced_data.AddressPerson', to='persons.person', verbose_name='Person'),
        ),
    ]
