# Generated by Django 5.2.6 on 2025-09-26 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('georeferenced_data', '0004_alter_address_active_alter_address_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='companies_addresses', through='georeferenced_data.AddressCompany', to='companies.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='addresscompany',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='companies.company', verbose_name='Firma'),
        ),
    ]
