# Generated by Django 5.2.6 on 2025-09-25 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='orders',
            field=models.ManyToManyField(through='orders.OrderClient', to='orders.order'),
        ),
        migrations.AddField(
            model_name='privateclient',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.person'),
        ),
        migrations.AddField(
            model_name='client',
            name='private_client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='clients.privateclient'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('private_client__isnull', True), ('business_client__isnull', False)), models.Q(('private_client__isnull', False), ('business_client__isnull', True)), _connector='OR'), name='private_client_true_and_business_client_false_or_private_client_false_and_business_client_true'),
        ),
    ]
