# Generated by Django 5.2.6 on 2025-09-26 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_businessclient_active_and_more'),
        ('companies', '0001_initial'),
        ('persons', '0003_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessclient',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='client',
            name='business_client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.businessclient', verbose_name='Geschäfstkunde'),
        ),
        migrations.AlterField(
            model_name='client',
            name='private_client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.privateclient', verbose_name='Privatkunde'),
        ),
        migrations.AlterField(
            model_name='privateclient',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.person', verbose_name='Person'),
        ),
    ]
