# Generated by Django 5.2.6 on 2025-09-25 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company_owner', to='persons.company', verbose_name='Firma')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='person_owner', to='persons.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Besitzer',
                'verbose_name_plural': 'Besitzer',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerator', models.IntegerField()),
                ('denominator', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Nummer')),
                ('order', models.ManyToManyField(related_name='order_properties', through='orders.OrderProperty', to='orders.order', verbose_name='Aufträge')),
                ('owners', models.ManyToManyField(related_name='owner_properties', through='properties.Ownership', to='properties.owner', verbose_name='Besitzer')),
            ],
            options={
                'verbose_name': 'Grundstück',
                'verbose_name_plural': 'Grundstücke',
            },
        ),
        migrations.AddField(
            model_name='ownership',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.property'),
        ),
        migrations.AddField(
            model_name='owner',
            name='properties',
            field=models.ManyToManyField(related_name='property_owners', through='properties.Ownership', to='properties.property', verbose_name='Grundstück'),
        ),
    ]
