# Generated by Django 5.2.6 on 2025-09-26 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company_owner', to='companies.company', verbose_name='Firma'),
        ),
    ]
