# Generated by Django 5.2.6 on 2025-09-26 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0002_alter_academictitle_active_alter_academictitle_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academictitle',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='academictitle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='academictitle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='academictitle',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='cadastralmunicipality',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='cadastralmunicipality',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='cadastralmunicipality',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='cadastralmunicipality',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='country',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='district',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='district',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='office',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='office',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='office',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='office',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='politicalmunicipality',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='politicalmunicipality',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='politicalmunicipality',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='politicalmunicipality',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='role',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='state',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='state',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
