# Generated by Django 5.2.6 on 2025-09-19 07:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEMail',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=100, verbose_name='E-Mail-Adresse')),
            ],
            options={
                'verbose_name': 'geschäftliche E-Mail-Adresse',
                'verbose_name_plural': 'geschäftliche E-Mail-Adressen',
            },
        ),
        migrations.CreateModel(
            name='BusinessPhoneNumber',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=100, verbose_name='Telefonnummer')),
            ],
            options={
                'verbose_name': 'geschäftliche Telefonnummer',
                'verbose_name_plural': 'geschäftliche Telefonnummern',
            },
        ),
        migrations.CreateModel(
            name='PrivateEMail',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=100, verbose_name='E-Mail-Adresse')),
            ],
            options={
                'verbose_name': 'private E-Mail-Adresse',
                'verbose_name_plural': 'private E-Mail-Adressen',
            },
        ),
        migrations.CreateModel(
            name='PrivatePhoneNumber',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=100, verbose_name='Telefonnummer')),
            ],
            options={
                'verbose_name': 'private Telefonnummer',
                'verbose_name_plural': 'private Telefonnummern',
            },
        ),
    ]
