# Generated by Django 5.2.6 on 2025-09-25 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correspondence', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessemail',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_email_address', to='persons.employee', verbose_name='Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='businessphonenumber',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_phone_number', to='persons.employee'),
        ),
        migrations.AddField(
            model_name='privateemail',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_email_address', to='persons.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='privatephonenumber',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_phone_number', to='persons.person'),
        ),
    ]
