# Generated by Django 5.2.6 on 2025-09-26 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0003_alter_businessemail_active_alter_businessemail_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessemail',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='businessemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='businessemail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='businessemail',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='businessphonenumber',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='businessphonenumber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='businessphonenumber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='businessphonenumber',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='privateemail',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='privateemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='privateemail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='privateemail',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='privatephonenumber',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='privatephonenumber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='privatephonenumber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='privatephonenumber',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
