# Generated by Django 5.2.6 on 2025-09-25 07:51

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStatus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Akt-Zustand',
                'verbose_name_plural': 'Akt-Zustände',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('number', models.IntegerField(verbose_name='Geschäftszahl')),
                ('parent_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='files.file', verbose_name='Vorakt')),
            ],
            options={
                'verbose_name': 'Akt',
                'verbose_name_plural': 'Akten',
            },
        ),
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='files.file', verbose_name='Datei')),
                ('file_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='files.filestatus', verbose_name='Dateistatus')),
            ],
            options={
                'verbose_name': 'Akt-Zustandsänderung',
                'verbose_name_plural': 'Akt-Zustandsänderungen',
                'ordering': ('date',),
            },
        ),
    ]
