# Generated by Django 5.2.6 on 2025-09-19 07:25

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStatus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Datei-Status',
                'verbose_name_plural': 'Datei-Status',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Nummer')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parents', to='files.file', verbose_name='übergeordnete Datei')),
            ],
            options={
                'verbose_name': 'Datei',
                'verbose_name_plural': 'Dateien',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='files.file', verbose_name='Datei')),
                ('file_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='files.filestatus', verbose_name='Datei-Status')),
            ],
            options={
                'verbose_name': 'Datei-Protokoll',
                'verbose_name_plural': 'Datei-Protokolle',
                'ordering': ('date',),
            },
        ),
    ]
