# Generated by Django 5.2.6 on 2025-09-25 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='parent_field',
        ),
        migrations.AddField(
            model_name='file',
            name='parent_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_file_child_files', to='files.file', verbose_name='Vorakt'),
        ),
    ]
