# Generated by Django 5.2.6 on 2025-09-25 11:32

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_file_parent_field_file_parent_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Akt', 'verbose_name_plural': 'Akte'},
        ),
        migrations.AlterField(
            model_name='file',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filestatus',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='filestatus',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='FileNote',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('note', models.TextField(verbose_name='Notize')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_file_notes', to='files.file', verbose_name='Akt')),
            ],
            options={
                'verbose_name': 'Akt-Notiz',
                'verbose_name_plural': 'Akt-Notizen',
            },
        ),
    ]
