# Generated by Django 5.2.6 on 2025-09-25 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_options_alter_file_active_alter_file_uuid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filelog',
            options={'ordering': ('date',), 'verbose_name': 'Zustandsänderung', 'verbose_name_plural': 'Zustandsänderungen'},
        ),
        migrations.AlterModelOptions(
            name='filenote',
            options={'verbose_name': 'Notiz', 'verbose_name_plural': 'Notizen'},
        ),
        migrations.AlterModelOptions(
            name='filestatus',
            options={'ordering': ('name',), 'verbose_name': 'Zustand', 'verbose_name_plural': 'Zustände'},
        ),
        migrations.AlterField(
            model_name='file',
            name='number',
            field=models.CharField(verbose_name='Geschäftszahl'),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='file_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='files.filestatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='filenote',
            name='note',
            field=models.TextField(verbose_name='Notiz'),
        ),
    ]
