# Generated by Django 5.2.6 on 2025-09-26 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_filelog_options_alter_filenote_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='filenote',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='filenote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='filenote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='filenote',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='filestatus',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='filestatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='filestatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='filestatus',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
