# Generated by Django 5.2.6 on 2025-09-25 07:51

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookups', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('brand', models.CharField(max_length=100, verbose_name='Marke')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='FIN')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Autos',
            },
        ),
        migrations.CreateModel(
            name='CarLicensePlate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_registration', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.car', verbose_name='Auto')),
            ],
            options={
                'verbose_name': 'Auto-Kennzeichen-Zuordnung',
                'verbose_name_plural': 'Auto-Kennzeichen-Zuordnungen',
            },
        ),
        migrations.CreateModel(
            name='CarLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('mileage', models.PositiveIntegerField(verbose_name='Kilometerstand')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.car', verbose_name='Auto')),
            ],
            options={
                'verbose_name': 'Fahrtprotokoll',
                'verbose_name_plural': 'Fahrtprotokolle',
            },
        ),
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('registration', models.CharField(max_length=100, unique=True, verbose_name='Kennzeichen')),
                ('cars', models.ManyToManyField(through='vehicles.CarLicensePlate', to='vehicles.car', verbose_name='Autos')),
            ],
            options={
                'verbose_name': 'Kennzeichen',
                'verbose_name_plural': 'Kennzeichen',
            },
        ),
        migrations.AddField(
            model_name='carlicenseplate',
            name='license_plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.licenseplate', verbose_name='Kennzeichen'),
        ),
        migrations.AddField(
            model_name='car',
            name='license_plates',
            field=models.ManyToManyField(through='vehicles.CarLicensePlate', to='vehicles.licenseplate', verbose_name='Kennzeichen'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_trips', to='persons.employee', verbose_name='Fahrer')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end_trips', to='lookups.politicalmunicipality', verbose_name='Ziel')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start_trips', to='lookups.politicalmunicipality', verbose_name='Start')),
            ],
            options={
                'verbose_name': 'Fahrt',
                'verbose_name_plural': 'Fahrten',
            },
        ),
        migrations.AlterUniqueTogether(
            name='carlicenseplate',
            unique_together={('car', 'license_plate')},
        ),
    ]
