# Generated by Django 5.2.6 on 2025-09-19 07:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('birth_date', models.DateField(verbose_name='Datum')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('gender', models.CharField(max_length=100, verbose_name='Geschlecht')),
                ('deceased', models.BooleanField(default=False, verbose_name='Verstorben')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personen',
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='UID')),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsidiary', to='persons.company', verbose_name='Mutterfirma')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmen',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='UID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department', to='persons.company', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Abteilung',
                'verbose_name_plural': 'Abteilungen',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='persons.company', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Mitarbeiter',
                'verbose_name_plural': 'Mitarbeiter',
            },
        ),
        migrations.CreateModel(
            name='EmployeeOrder',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='orders',
            field=models.ManyToManyField(related_name='employee', through='persons.EmployeeOrder', to='orders.order', verbose_name='Aufträge'),
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalEmployee',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_security_number', models.IntegerField(verbose_name='SVN')),
                ('wage', models.IntegerField(help_text='Stundengehalt in Cent', verbose_name='Stundengehalt')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='internal_employee', to='persons.employee', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'interner Mitarbeiter',
                'verbose_name_plural': 'interne Mitarbeiter',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='persons.person', verbose_name='Person'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField()),
                ('employees', models.ManyToManyField(through='persons.EmployeeRole', to='persons.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employeerole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(related_name='employee', through='persons.EmployeeRole', to='persons.role', verbose_name='Rollen'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orders', models.ManyToManyField(blank=True, related_name='orders_clients', through='orders.OrderClient', to='orders.order', verbose_name='Aufträge')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corporate_client', to='persons.person', verbose_name='Firma')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='private_client', to='persons.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
                'constraints': [models.CheckConstraint(condition=models.Q(('person__isnull', True), ('company__isnull', False), ('person__isnull', False), ('company__isnull', True)), name='person_true_and_company_false_or_person_false_and_company_true')],
            },
        ),
    ]
