# Generated by Django 5.2.6 on 2025-09-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_client_active_alter_client_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.CharField(max_length=100, null=True, verbose_name='ID'),
        ),
    ]
