# Generated by Django 5.2.6 on 2025-09-26 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('finances', '0004_remove_bankaccount_companies_and_more'),
        ('persons', '0003_person_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='company',
            name='parent_company',
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='companies.company', verbose_name='Firma'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='bank_account',
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
