# Generated by Django 5.2.6 on 2025-09-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_delete_bankaccount_delete_invoice_and_more'),
        ('georeferenced_data', '0005_alter_address_company_alter_addresscompany_company'),
        ('persons', '0004_remove_company_bank_account_and_more'),
        ('properties', '0002_alter_owner_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
