# Generated by Django 5.2.6 on 2025-09-26 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_delete_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.AlterField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='person',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='persons.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='employeeorder',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='employeeorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='employeeorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='employeeorder',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='internalemployee',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='internalemployee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='internalemployee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='internalemployee',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'männlich'), ('female', 'weiblich'), ('diverse', 'divers')], max_length=100, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='role',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
