# Generated by Django 5.2.6 on 2025-09-25 07:51

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('iban', models.CharField(verbose_name='IBAN')),
            ],
            options={
                'verbose_name': 'Bankverbindung',
                'verbose_name_plural': 'Bankverbindungen',
                'ordering': ('iban',),
            },
        ),
        migrations.CreateModel(
            name='CounterOffer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('external_id', models.IntegerField(blank=True, null=True, verbose_name='externe ID')),
                ('net_amount', models.IntegerField(help_text='Nettobetrag in Cent', verbose_name='Nettobetrag')),
                ('notes', models.TextField(verbose_name='Notizen')),
            ],
            options={
                'verbose_name': 'Gegenangebot',
                'verbose_name_plural': 'Gegenangebote',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('net_amount', models.IntegerField(help_text='Nettobetrag in Cent', verbose_name='Nettobetrag')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
            },
        ),
        migrations.CreateModel(
            name='InvoiceOrder',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Rechnung-Auftrag-Zuordnung',
                'verbose_name_plural': 'Rechnungen-Auftrag-Zuordnungen',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('external_id', models.IntegerField(blank=True, null=True, verbose_name='externe ID')),
                ('net_amount', models.IntegerField(help_text='Nettobetrag in Cent', verbose_name='Nettobetrag')),
                ('notes', models.TextField(verbose_name='Notizen')),
            ],
            options={
                'verbose_name': 'Angebot',
                'verbose_name_plural': 'Angebote',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Auftragsdatum')),
                ('internal_id', models.IntegerField(blank=True, null=True, verbose_name='interne ID')),
                ('external_id', models.IntegerField(blank=True, null=True, verbose_name='externe ID')),
                ('net_amount', models.IntegerField(help_text='Nettobetrag in Cent', verbose_name='Nettobetrag')),
                ('notes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Notizen')),
            ],
            options={
                'verbose_name': 'Auftrag',
                'verbose_name_plural': 'Aufträge',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('amount', models.PositiveIntegerField(help_text='Betrag in Cent', verbose_name='Betrag')),
            ],
            options={
                'verbose_name': 'Zahlung',
                'verbose_name_plural': 'Zahlungen',
                'ordering': ('date',),
            },
        ),
    ]
