# Generated by Django 5.2.6 on 2025-09-25 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        ('orders', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='company_bank_accounts', to='persons.company', verbose_name='Firmen'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='persons',
            field=models.ManyToManyField(blank=True, related_name='person_bank_accounts', to='persons.person', verbose_name='Personen'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver_invoice', to='persons.client', verbose_name='Empfänger'),
        ),
        migrations.AddField(
            model_name='invoiceorder',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.invoice', verbose_name='Rechnung'),
        ),
        migrations.AddField(
            model_name='invoiceorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='Auftrag'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='orders',
            field=models.ManyToManyField(related_name='orders_invoices', through='finances.InvoiceOrder', to='orders.order', verbose_name='Aufträge'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to='persons.client', verbose_name='Kunde'),
        ),
    ]
