# Generated by Django 5.2.6 on 2025-09-19 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        ('orders', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver_invoice', to='persons.client', verbose_name='Empfänger'),
        ),
        migrations.AddField(
            model_name='invoiceorder',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.invoice', verbose_name='Rechnung'),
        ),
        migrations.AddField(
            model_name='invoiceorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='Auftrag'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='orders',
            field=models.ManyToManyField(related_name='orders_invoices', through='finances.InvoiceOrder', to='orders.order', verbose_name='Aufträge'),
        ),
    ]
