# Generated by Django 5.2.6 on 2025-09-25 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='counteroffer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='counteroffer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoiceorder',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoiceorder',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
