# Generated by Django 5.2.6 on 2025-09-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_bankaccount_active_alter_bankaccount_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='persons',
        ),
        migrations.DeleteModel(
            name='CounterOffer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='invoiceorder',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceorder',
            name='order',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
