# Generated by Django 5.2.6 on 2025-09-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_remove_bankaccount_companies_and_more'),
        ('persons', '0004_remove_company_bank_account_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
