# Generated by Django 5.2.6 on 2025-09-25 07:51

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Zustimmung',
                'verbose_name_plural': 'Zustimmungen',
            },
        ),
        migrations.CreateModel(
            name='ConsentFormRequests',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
            ],
            options={
                'verbose_name': 'Zustimmungserklärung-Anfrage',
                'verbose_name_plural': 'Zustimmungserklärung-Anfragen',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Teilung',
                'verbose_name_plural': 'Teilungen',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
            ],
            options={
                'verbose_name': 'Auftrag',
                'verbose_name_plural': 'Aufträge',
            },
        ),
        migrations.CreateModel(
            name='OrderClient',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Auftrag-Kunde-Zuordnung',
                'verbose_name_plural': 'Auftrag-Kunde-Zuordnungen',
            },
        ),
        migrations.CreateModel(
            name='OrderContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Auftrag-Kontakt-Beziehung',
                'verbose_name_plural': 'Auftrag-Kontakt-Beziehungen',
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
            ],
            options={
                'verbose_name': 'Auftrag-Protokoll',
                'verbose_name_plural': 'Auftrag-Protokolle',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='OrderProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Auftrag-Status',
                'verbose_name_plural': 'Auftrag-Status',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Auftrag-Art',
                'verbose_name_plural': 'Auftrag-Arten',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ConsentFormReplies',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('consent_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_form_replies', to='orders.consentform', verbose_name='Einverständnis')),
            ],
            options={
                'verbose_name': 'Zustimmungserklärung-Antwort',
                'verbose_name_plural': 'Zustimmungserklärung-Antworten',
            },
        ),
    ]
