# Generated by Django 5.2.6 on 2025-09-25 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('contacts', '0002_initial'),
        ('files', '0001_initial'),
        ('orders', '0001_initial'),
        ('persons', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentformreplies',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_form_replies', to='persons.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='consentformrequests',
            name='consent_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_form_requests', to='orders.consentform', verbose_name='Einverständnis'),
        ),
        migrations.AddField(
            model_name='consentformrequests',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_orders', to='files.file', verbose_name='Geschäftsfall'),
        ),
        migrations.AddField(
            model_name='division',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_types', to='orders.order', verbose_name='Auftrag'),
        ),
        migrations.AddField(
            model_name='orderclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Kunde'),
        ),
        migrations.AddField(
            model_name='orderclient',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='Auftrag'),
        ),
        migrations.AddField(
            model_name='order',
            name='clients',
            field=models.ManyToManyField(related_name='client_orders', through='orders.OrderClient', to='clients.client', verbose_name='Kunden'),
        ),
        migrations.AddField(
            model_name='ordercontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='ordercontact',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='contacts',
            field=models.ManyToManyField(related_name='contact_orders', through='orders.OrderContact', to='contacts.contact', verbose_name='Kontakte'),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='Auftrag'),
        ),
        migrations.AddField(
            model_name='orderproperty',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='Auftrag'),
        ),
        migrations.AddField(
            model_name='orderproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.property', verbose_name='Grundstück'),
        ),
        migrations.AddField(
            model_name='order',
            name='properties',
            field=models.ManyToManyField(related_name='property_orders', through='orders.OrderProperty', to='properties.property', verbose_name='Grundstücke'),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus', verbose_name='Auftrag-Status'),
        ),
    ]
