# Generated by Django 5.2.6 on 2025-09-19 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('finances', '0002_initial'),
        ('orders', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentformreplies',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_form_replies', to='persons.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='consentformrequests',
            name='consent_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_form_requests', to='orders.consentform', verbose_name='Einverständnis'),
        ),
        migrations.AddField(
            model_name='consentformrequests',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.contract'),
        ),
        migrations.AddField(
            model_name='order',
            name='employees',
            field=models.ManyToManyField(related_name='employees_orders', through='persons.EmployeeOrder', to='persons.employee', verbose_name='Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_order', to='files.file', verbose_name='Datei'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoices',
            field=models.ManyToManyField(related_name='invoices_orders', through='finances.InvoiceOrder', to='finances.invoice', verbose_name='Rechnung'),
        ),
        migrations.AddField(
            model_name='division',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_types', to='orders.order', verbose_name='Auftrag'),
        ),
        migrations.AddField(
            model_name='orderclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.client', verbose_name='Kunde'),
        ),
        migrations.AddField(
            model_name='orderclient',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='Auftrag'),
        ),
        migrations.AddField(
            model_name='order',
            name='clients',
            field=models.ManyToManyField(related_name='clients_orders', through='orders.OrderClient', to='persons.client', verbose_name='Kunde'),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='Auftrag'),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus', verbose_name='Auftrag-Status'),
        ),
    ]
