# Generated by Django 5.2.6 on 2025-09-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_consentform_active_alter_consentform_uuid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderlog',
            options={'ordering': ('date',), 'verbose_name': 'Zustandsänderung', 'verbose_name_plural': 'Zustandsänderungen'},
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.CharField(max_length=100, null=True, verbose_name='ID'),
        ),
    ]
