# Generated by Django 5.2.6 on 2025-09-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderlog_options_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='char_id',
        ),
    ]
