# Generated by Django 5.2.6 on 2025-09-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_id_order_char_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='char_id',
            new_name='id',
        ),
    ]
