# Generated by Django 5.2.6 on 2025-09-26 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_char_id_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentform',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='consentformreplies',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='consentformreplies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='consentformreplies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='consentformreplies',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='consentformrequests',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='consentformrequests',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='consentformrequests',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='consentformrequests',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='division',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='division',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='division',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='division',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am'),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='verändert am'),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
