# Generated by Django 5.2.6 on 2025-09-25 07:51

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Arbeit',
                'verbose_name_plural': 'Arbeiten',
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('duration', models.DurationField(verbose_name='Dauer')),
                ('internal_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_employee_work_logs', to='persons.internalemployee', verbose_name='interner Arbeitnehmer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_work_logs', to='orders.order', verbose_name='Auftrag')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='works.work', verbose_name='Arbeit')),
            ],
            options={
                'verbose_name': 'Arbeitsprotokoll',
                'verbose_name_plural': 'Arbeitsprotokolle',
                'ordering': ('date',),
            },
        ),
    ]
